### PR TITLE
Adding opinionated default configuration

### PR DESCRIPTION
**Pull request by Tubaleviao**
Hello I really liked this project! 

I added some opinionated configuration because I think that it would be nicer to make it work by default. 
This way, the library won't throw an error if we try to pass just the first parameter to it.

### CODE REVIEW

**Comment by savioxavier** [comment]
Thanks a lot for taking an interest in this repository! Please see the above comments, there might be a few fixes.

I'll add the label as well, since you're coming from Hacktoberfest.

**Comment by Tubaleviao** [comment]
@savioxavier thanks for the label! But could you please help me with which comments you are talking about? I couldn't find any

**Comment by savioxavier** [comment]
Ah, I was talking about the review comments. In case you're not able to view them, here they are:
(2 images)
image
image

**Review by savioxavier — CHANGES_REQUESTED** [review]

**Comment by savioxavier** [comment]
I actually forgot to click on "Start a review", my bad :(

**Comment by Tubaleviao** [comment]
No worries! I applied the changes as requested!

**Review by savioxavier — APPROVED** [review]

**Comment by savioxavier** [comment]
Thanks for your contribution!

**Pull request merged**
